# Generated by Django 5.1.4 on 2025-01-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[(None, '----Pilih Status----'), ('Hadir', 'Hadir'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Tanpa Keterangan', 'Tanpa Keterangan')], default=('Hadir', 'Hadir'), max_length=20, verbose_name='Status'),
        ),
    ]
