# Generated by Django 5.1.4 on 2025-01-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(verbose_name='Tanggal'),
        ),
    ]
