# Generated by Django 5.1.4 on 2025-01-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[(None, '----Pilih Status----'), ('Hadir', 'Hadir'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Tanpa Keterangan', 'Tanpa Keterangan')], default='Hadir', max_length=20, verbose_name='Status'),
        ),
    ]
