# Generated by Django 5.1.4 on 2025-01-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_report_reporter_alter_report_subtitute_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='duty',
            field=models.TextField(blank=True, help_text='Opsional. Jika ada', max_length=250, null=True, verbose_name='Tugas'),
        ),
    ]
