# Generated by Django 5.1.4 on 2025-01-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_report_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='notes',
            field=models.TextField(blank=True, help_text='Opsional. Jika ada', max_length=250, null=True, verbose_name='Keterangan'),
        ),
    ]
