# Generated by Django 5.1.4 on 2025-02-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_report_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Sudah complete'),
        ),
        migrations.AddField(
            model_name='report',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='Sudah di-submit?'),
        ),
    ]
