# Generated by Django 5.1.4 on 2025-01-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[(None, '----Pilih Kategori----'), ("Syar'i", "Syar'i"), ('Ashri', 'Ashri')], default=("Syar'i", "Syar'i"), max_length=20, verbose_name='Kode Pelajaran'),
        ),
    ]
