# Generated by Django 5.1.4 on 2025-01-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[(None, '----Pilih Kategori----'), ("Syar'i", "Syar'i"), ('Ashri', 'Ashri')], default="Syar'i", max_length=20, verbose_name='Kode Pelajaran'),
        ),
    ]
