# Generated by Django 5.1.4 on 2025-01-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_course_short_name_alter_course_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[(None, '----Pilih Kategori----'), ("Syar'i", "Syar'i"), ('Ashri', 'Ashri'), ('Netral', 'Netral')], default="Syar'i", max_length=20, verbose_name='Kategori'),
        ),
    ]
