# Generated by Django 5.1.4 on 2025-01-09 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_schedule_options_alter_schedule_schedule_day_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-schedule_day', 'schedule_class', 'schedule_time'], 'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedules'},
        ),
    ]
