# Generated by Django 5.1.4 on 2025-01-11 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_alter_schedule_schedule_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='time_end',
            field=models.TimeField(default=datetime.time(23, 45, 19, 887261), verbose_name='Waktu Akhir'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_start',
            field=models.TimeField(default=datetime.time(23, 45, 19, 887261), verbose_name='Waktu Mulai'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_time',
            field=models.CharField(choices=[('1', 'Jam ke-1'), ('2', 'Jam ke-2'), ('3', 'Jam ke-3'), ('4', 'Jam ke-4'), ('5', 'Jam ke-5'), ('6', 'Jam ke-6'), ('7', 'Jam ke-7'), ('8', 'Jam ke-8'), ('9', 'Jam ke-9')], max_length=20, verbose_name='Jam Ke-'),
        ),
    ]
