# Generated by Django 5.1.4 on 2025-01-13 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_schedule_time_end_schedule_time_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time_end',
            field=models.TimeField(default=datetime.time(14, 30, 38, 424815), verbose_name='Waktu Akhir'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_start',
            field=models.TimeField(default=datetime.time(14, 30, 38, 424815), verbose_name='Waktu Mulai'),
        ),
    ]
