# Generated by Django 5.1.4 on 2025-01-13 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_alter_schedule_time_end_alter_schedule_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time_end',
            field=models.TimeField(default=datetime.time(7, 0), verbose_name='Waktu Akhir'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_start',
            field=models.TimeField(default=datetime.time(7, 0), verbose_name='Waktu Mulai'),
        ),
    ]
